[book]
title = "GTK Brotway"
description = "A GTK Broadway backend fork"
authors = ["Lev Gorodetskii"]
language = "en"
src = "src"

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
additional-css = ["theme/adwaita.css"]
additional-js = ["theme/fold-rows.js"]
git-repository-url = "https://github.com/droserasprout/gtk-brotway"
edit-url-template = "https://github.com/droserasprout/gtk-brotway/edit/ci/docs/{path}"

[output.html.fold]
enable = true
level = 0
